### ISSUE TITLE
Reset mechanism for data

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/polls-api#10]
Actual backend for the api is completely polluted by tests made by the users time after time.
At this time, the question **What is your favourite programming language** is preset 87 times, making very difficult (and a bit boring as well) work on it.

I would suggest

1. Provide more sample polls (one question is not enough. At least 5 would be good)
2. While it would be great to keep polls results (the votes), I'd suggest to reset/remove all but default questions every hour, every day, or every-what-you-want

**Comment by kylef** [comment]
I was thinking about this, and perhaps when a question is created that already exists. We return a 200 and expose the original question instead of creating new ones. This means questions will be unique.

**Comment by XVincentX** [comment]
Are you sure it is already in this way?
I am getting several duplicates here

![image](https://cloud.githubusercontent.com/assets/1416224/7461855/633cd7ca-f2ad-11e4-954d-a20d198114a5.png)

**Comment by kylef** [comment]
Oh, I was suggesting we do this. Not saying it was already done.

**Comment by XVincentX** [comment]
Whops! Sorry, my mistake.
