### ISSUE TITLE
Enabling CORS header

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/polls-api#5]
Would be possible to enable CORS for this reference implementation?

This would be great to develop web applications on top of that.
[Test case](http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fpolls.apiblueprint.org&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

**Comment by whitedevil89** [comment]
AFAIK it's the server that should care about CORS. Maybe I just misunderstood the problem.

By the way, back in time I used [this](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) on chrome to enable CORS on my local machine. Dunno if it can be useful now.

**Comment by kylef** [comment]
Certainly can, I'll add this soon.
