### ISSUE TITLE
Http batching

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/polls-api#9]
Would be possible to enable Http Batching of requests?

**Comment by kylef** [comment]
I'm not sure what you mean by HTTP Batching, can you point me to an RFC or specification describing this?

**Comment by XVincentX** [comment]
Sure!
[IEFT reference](https://tools.ietf.org/id/draft-snell-http-batch-00.html)
[Facebook example](https://developers.facebook.com/docs/graph-api/making-multiple-requests)
[Google example](https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch)
[Angular module](https://github.com/jonsamwell/angular-http-batcher)
